name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, dev-ue1]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode verify